### PR TITLE
Added optional delay to presentPopupBarWithContentViewController

### PR DESCRIPTION
**Pull request by MaticConradi**

### CODE REVIEW

**Comment by iDevelopper** [comment]
I do not agree with this PR as it's delete an existing method. Also, this can be done easily with a perform selector after delay... But it is not my library.

**Comment by MaticConradi** [comment]
@iDevelopper what do you mean by 

> it's delete an existing method

I don't delete any existing methods, you can still use your code without changing anything. Am I missing something?

**Comment by iDevelopper** [comment]
My apologies! Your modifications are in private files. Sorry!

**Comment by LeoNatan** [comment]
Hello,

Thanks for taking the time submitting this pull request.
Could you please elaborate on the use case here? Why delay the presentation using API rather than use something like `dispatch_after` to present after delay?

**Comment by MaticConradi** [comment]
Well, it’s cleaner and easier to use. As far as I know it also plays nicely with animation interruptions. One problem in my app with using dispatch_after was that you couldn’t quickly switch between tabs without the wrong popup bar appearing.

**Comment by LeoNatan** [comment]
What worries me with this kind of approach is issues with state management. A popup controller is set to be in transition state before the animation, but then a delay happens and the animation is interrupted. The state will remain broken. The code is already too complex, and I'm not sure this won't be additional complexity.

**Comment by MaticConradi** [comment]
I’m not really familiar with the entire code base. I’ve been using this approach for months now and everything works fine (or at least it looks like it does). Maybe you should take a look at the state management and test it with the delay included. Or you could just wait until v3.0 and see what’s doable then

**Comment by LeoNatan** [comment]
v3 started as something relatively contained (animations during presentation), but I want to look at other things, such as using the system custom presentation capabilities. I am not full capacity on v3 for now, but I will take a look.

**Pull request closed without merging**
