### PR TITLE
Added cocoapods support

### PR DESCRIPTION
**Pull request by zmian**

### CODE REVIEW

**Comment by werediver** [comment]
CocoaPods support would be great feature!

**Comment by LeoNatan** [comment]
Hi,

Thanks for this PR. As I have stated in the past, I am not interested in CocoaPods support. I believe the way forward is Carthage and possibly something that may come from Apple. 

Thanks

**Comment by CoBrA2168** [comment]
I really wish you would reconsider, since I would like to integrate this into a project which already uses Cocoapods.

**Comment by LeoNatan** [comment]
You can. Carthage does not stop you from doing so, just allows a much more cleaner way to integrate modern frameworks.

**Pull request closed without merging**
