### PR TITLE
minor update: change spelling

### PR DESCRIPTION
**Pull request by aregler**
This PR should just change the spelling of "Gesutre" and change it to "Gesture".
Have a nice day 👋🏻

### CODE REVIEW

**Comment by LeoNatan** [comment]
Oh dear 🤦‍♂️
It’s amazing how years can go by without noticing such mistakes. 
Thank you!

**Comment by iDevelopper** [comment]
Hello @LeoNatan,

There is also:
```
- (void)_setTitleLableFontsAccordingToBarStyleAndTint
```

Cheers,

**Comment by LeoNatan** [comment]
It's lablè, from French 🤣😂
I'll fix it if I remember. If you want, pls submit a small PR.

**Comment by LeoNatan** [comment]
@iDevelopper Fixed.

**Comment by iDevelopper** [comment]
Ah! Ok, I was preparing a little pull request!

**Pull request merged**
