### PR TITLE
Let's add a vibrancy effect to the popup close button.

### PR DESCRIPTION
**Pull request by iDevelopper**
Add a vibrancy effect to the popup close button if its style is chevron and user provides a content visual effect view.

### CODE REVIEW

**Comment by LeoNatan** [comment]
Hello,

I like the effect, but I don't like the user supplying an effect view, which is then only used when the popup button is of chevron style. There are issues in this implementation, such as what happens of the button style is changed after setting a user content effect view?

I think this is better left to implementations by users, rather than complicating the framework.

**Comment by LeoNatan** [comment]
Maybe another approach is to give the option to the user to provide a view where the button will be added. Then, if the user creates the correct hierarchy (effect view -> vibrancy effect view) and provides that, the button will look as expected.

**Comment by iDevelopper** [comment]
Hello,

>  such as what happens of the button style is changed after setting a user content effect view?

Yes, I should have planned a setter for popupCloseButtonStyle.

Otherwise, you changed a lot of things about the close button and these changes are not tagged yet. So I'll wait for the 2.10.7 release. Perhaps with the second approach. You mean that the user himself provides the vibrancy effect view and if so we add the close button in it?

Other question: How can we edit the code when using SPM dependency in a project? Thanks.

**Comment by LeoNatan** [comment]
I’ll have a solution for this tonight. I already implemented something, just need to document it. Even made the music demo use it.

**Pull request closed without merging**
