### PR TITLE
Fix font on Prominent bar style

### PR DESCRIPTION
**Pull request by llsc12**
The font was too bold.

### CODE REVIEW

**Comment by LeoNatan** [comment]
I like the current fonts. 
Please post screenshots for comparisons, of different text sizes.
Thanks

**Comment by llsc12** [comment]
image

my changes basically reverted changes made to the prominent bar style's title font
image

**Comment by LeoNatan** [comment]
You also changed how the font responds to resizing. 

The issue is that Apple changes font sizes and weights with every iOS version (the prominent bar came out with iOS 10 and is still present in Podcasts, and has slightly changed with each version and sometimes between the two apps). So I finally allowed myself some creative control over fonts and spacing. 

You can set the font you wish to have in the LNPopupBarAppearance object.

**Comment by LeoNatan** [comment]
I’ll take a look at fonts again.

**Comment by llsc12** [comment]
my apologies, but thank you for sharing this information.

**Comment by LeoNatan** [comment]
I just pixel-peeped the prominent bar in the iOS 17 Podcasts app and mine, and managed to get the titles pixel perfect, including the spacing between them.

image

The title weight is definitely "medium", not "regular". The subtitle is "regular". Both are size 15.

**Comment by LeoNatan** [comment]
Please test with the last release. I am closing this PR for now.

**Comment by LeoNatan** [comment]
Sorry, I didn't past the image above correctly:

image

You can see the 1:1 pixel overlap.

**Pull request closed without merging**
