### PR TITLE
add Support For Carthage

### PR DESCRIPTION
**Pull request by CodeEagle**
add Support For Carthage

### CODE REVIEW

**Comment by LeoNatan** [comment]
Hi,

Thanks for your PR.
Does this commit include everything from #25?

**Comment by CodeEagle** [comment]
no, just add shared scheme and you need to tag a version to support Carthage

**Comment by LeoNatan** [comment]
Sorry, I somehow saw two pull requests.

Can you elaborate a little? Carthage support has been on my todo on a while, but never got to it, so I would like to learn something here. :smile: Adding a shared scheme + create a tag in Git is all that is needed? Sound very easy, much better than CocoaPods.

**Comment by CodeEagle** [comment]
yeah, just that easy. every time you release a version , just tag it.

**Pull request merged**
